name: 'Setup Kicad'
description: 'Setup Kicad'

inputs:
  version:
    description: 'The Kicad "major.minor" version to use. This action cannot enforce a micro version'
    required: true
    default: '9.0'

outputs:
  version:
    description: 'The installed Kicad version'
    value: ${{ steps.dump.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Check runner OS
      if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error title=Error hint::This action supports only linux"
        exit 1
      shell: bash

    # TODO: validate version

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:kicad/kicad-${{ inputs.version }}-releases
        sudo apt update
        sudo apt install -y --no-install-recommends kicad
      shell: bash

    - name: Dump version
      id: dump
      run: |
        kicad-cli -v
        echo "version=$(kicad-cli -v)" >> $GITHUB_OUTPUT
      shell: bash
